# Generated by Django 5.0.6 on 2024-05-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_mycar_car_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='address_user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='city_user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fname',
            new_name='fname_user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='gender',
            new_name='gender_user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='mobile_user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='state_user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='usern',
            new_name='usern_user',
        ),
    ]
