# Generated by Django 5.0.6 on 2024-05-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_address_customer_address_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_user',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='city_user',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email_user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fname_user',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='gender_user',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobile_user',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='state_user',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='usern_user',
            new_name='usern',
        ),
    ]
