# Generated by Django 5.0.6 on 2024-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_customer_password_driver_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
