# Generated by Django 5.0.6 on 2024-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_language_customer_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='customer',
            name='languages',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
