# Generated by Django 5.0.6 on 2024-06-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_calendardata_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
