# Generated by Django 5.0.6 on 2024-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_driver_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
