# Generated by Django 5.0.7 on 2024-08-12 23:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('day', models.CharField(max_length=20)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('username', models.CharField(default='default_username', max_length=150)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255)),
                ('service_duration', models.IntegerField()),
                ('service_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_day', models.CharField(max_length=50)),
                ('selected_date', models.CharField(max_length=50)),
                ('selected_time', models.CharField(max_length=50)),
                ('payment_status', models.CharField(default='success', max_length=50)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(default='default', max_length=150)),
                ('driver_username', models.CharField(default='default', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('checkbox', models.BooleanField(default=False)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('username', models.CharField(default='', max_length=150)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('password', models.CharField(default='default_password', max_length=200)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(default='Unknown', max_length=20)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('languages_spoken', models.CharField(blank=True, max_length=500, null=True)),
                ('services', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('usern', models.OneToOneField(blank=True, default=None, max_length=80, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('password', models.CharField(default='default_password', max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=4, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('languages', models.CharField(blank=True, max_length=500, null=True)),
                ('usern', models.OneToOneField(blank=True, default=None, max_length=80, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
