# Generated by Django 5.0.7 on 2024-08-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_district_alter_mentor_usern'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
