# Generated by Django 5.0.6 on 2024-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
