# Generated by Django 5.0.6 on 2024-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_driver_city_driver_gender_driver_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='default_password', max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='default_password', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='usern',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='usern',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
