# Generated by Django 5.0.6 on 2024-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_customer_college_customer_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='languages',
            field=models.ManyToManyField(blank=True, to='website.language'),
        ),
    ]
