# Generated by Django 5.0.6 on 2024-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_customer_languages_delete_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='services',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='year_of_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
