# Generated by Django 5.0.6 on 2024-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_driver_description_driver_languages_spoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('checkbox', models.BooleanField(default=False)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
