# Generated by Django 5.0.6 on 2024-06-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_calendardata'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardata',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
