# Generated by Django 5.0.6 on 2024-06-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_calendardata_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='calendardata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
