# Generated by Django 5.0.6 on 2024-06-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_deletedschedule_calendardata_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendardata',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='deletedschedule',
            name='username',
            field=models.CharField(default='default_username', max_length=150),
        ),
    ]
