# Generated by Django 5.0.6 on 2024-07-05 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletedschedule',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='driver_username',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='usern',
            field=models.OneToOneField(blank=True, default=None, max_length=80, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driver',
            name='usern',
            field=models.OneToOneField(blank=True, default=None, max_length=80, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
